# @package eval.tofu.metrics.forget_Q_A_Prob
defaults:
  - ../../data/datasets@datasets: TOFU_QA_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: 32

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.tofu.forget_split}