# @package eval.tofu.metrics.mia_gradnorm
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: mia_gradnorm
batch_size: 1
p: 2

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.tofu.forget_split}
  TOFU_QA_holdout:
    args:
      hf_args:
        name: ${eval.tofu.holdout_split}