# @package eval.tofu.metrics.ra_Q_A_ROUGE
defaults:
  - ../../data/datasets@datasets: TOFU_QA_ra
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  
  # ^ get default dataset and generation config information

handler: rouge
rouge_type: rougeL_recall
batch_size: 32
datasets: # override as needed
  TOFU_QA_ra:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left